'use strict';
const KEY='sports_dairo_final_v2';
const seed={products:[
{id:1,sku:'SD001',name:'Zapatillas Urban Sport',cat:'Calzado',price:249,buy:160,stock:12,min:3,emoji:'👟'},
{id:2,sku:'SD002',name:'Polo Deportivo Premium',cat:'Ropa',price:89,buy:50,stock:20,min:5,emoji:'👕'},
{id:3,sku:'SD003',name:'Casaca Deportiva',cat:'Ropa',price:179,buy:105,stock:8,min:3,emoji:'🧥'},
{id:4,sku:'SD004',name:'Balón de Fútbol',cat:'Fútbol',price:89,buy:52,stock:15,min:4,emoji:'⚽'},
{id:5,sku:'SD005',name:'Mochila Deportiva',cat:'Accesorios',price:129,buy:75,stock:9,min:3,emoji:'🎒'},
{id:6,sku:'SD006',name:'Audífonos Bluetooth',cat:'Tecnología',price:99,buy:55,stock:14,min:4,emoji:'🎧'},
{id:7,sku:'SD007',name:'Smartwatch Deportivo',cat:'Tecnología',price:159,buy:95,stock:7,min:3,emoji:'⌚'},
{id:8,sku:'SD008',name:'Parlante Portátil',cat:'Tecnología',price:119,buy:68,stock:10,min:3,emoji:'🔊'},
{id:9,sku:'SD009',name:'Ventilador USB',cat:'Artefactos',price:69,buy:38,stock:11,min:3,emoji:'🌀'},
{id:10,sku:'SD010',name:'Lámpara LED',cat:'Artefactos',price:59,buy:31,stock:18,min:5,emoji:'💡'}],sales:[],purchases:[],customers:[],orders:[],cart:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed; if(!db.products)db=seed;
const $=id=>document.getElementById(id), money=n=>'S/ '+Number(n||0).toFixed(2), save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sum=(a,f)=>a.reduce((x,y)=>x+f(y),0); const subtotal=()=>sum(db.cart,x=>x.price*x.qty); const igv=n=>+(n*0.18).toFixed(2); const total=()=>+(subtotal()+igv(subtotal())).toFixed(2);
let adminSession=localStorage.getItem('sports_dairo_admin_session')==='1';
const ADMIN_USER='admin', ADMIN_PASS='admin123';
function requireAdmin(page='dashboard'){
  if(adminSession){ App.admin(page); return; }
  App.adminLoginScreen(page);
}
const App={
shop(cat=''){ $('view').innerHTML=`<section class="hero"><div><small>SPORTS DAIRO</small><h1>EQUÍPATE PARA<br><em>GRANDES MOMENTOS</em></h1><p>Zapatillas, ropa, accesorios tecnológicos y pequeños artefactos.</p><button class="primary" onclick="document.getElementById('products').scrollIntoView({behavior:'smooth'})">Ver productos →</button></div><div class="hero-art">EL DEPORTE<br><em>TE HACE GRANDE</em></div></section><div class="cats">${[['Calzado','👟'],['Ropa','👕'],['Fútbol','⚽'],['Accesorios','🎒'],['Tecnología','🎧'],['Artefactos','💡']].map(x=>`<div class="cat" onclick="App.shop('${x[0]}')"><div class="ico">${x[1]}</div>${x[0]}</div>`).join('')}</div><section id="products" class="section"><div class="section-head"><h2>Productos destacados</h2><span>${cat||'Todos los productos'}</span></div><div id="grid" class="grid"></div></section><div class="badges"><div class="badge">⚽<b>FÚTBOL</b><small>JUEGA SIN LÍMITES</small></div><div class="badge">🏋️<b>FITNESS</b><small>TU MEJOR VERSIÓN</small></div><div class="badge">🎧<b>TECNOLOGÍA</b><small>INNOVACIÓN PARA TI</small></div></div><section class="about"><h2>Sobre nosotros</h2><p>SPORTS DAIRO · RUC 10757165530 · Ica, Chincha Alta · 928 469 185 · Dairo.kick@gmail.com</p></section>`; App.renderProducts(cat); window.scrollTo({top:0,behavior:'smooth'}); },
renderProducts(cat=''){let q=($('search')?.value||'').toLowerCase();let a=db.products.filter(p=>(!cat||p.cat===cat)&&(`${p.name} ${p.sku} ${p.cat}`).toLowerCase().includes(q));$('grid').innerHTML=a.length?a.map(p=>`<article class="product"><div class="pic">${p.emoji}</div><small>${esc(p.sku)} · ${esc(p.cat)}</small><h3>${esc(p.name)}</h3><div class="stars">★★★★★</div><span class="price">${money(p.price)}</span> <span class="old">${money(p.price*1.25)}</span><small> · Stock ${p.stock}</small><button class="primary" ${p.stock<1?'disabled':''} onclick="App.add(${p.id})">${p.stock?'Agregar al carrito':'Sin stock'}</button></article>`).join(''):'<div class="empty">No hay productos para esta búsqueda.</div>'},
add(id){let p=db.products.find(x=>x.id===id);if(!p||p.stock<1)return;let x=db.cart.find(x=>x.id===id);if(x&&x.qty>=p.stock)return alert('No hay más stock disponible.');x?x.qty++:db.cart.push({id:p.id,name:p.name,price:p.price,qty:1});save();App.updateCart();App.cart()},
updateCart(){ $('cartCount').textContent=sum(db.cart,x=>x.qty);$('cartTotal').textContent=money(total());},
cart(){let rows=db.cart.map((x,i)=>`<div class="cart-row"><div><b>${esc(x.name)}</b><br><small>${money(x.price)} · cantidad ${x.qty}</small></div><div><b>${money(x.price*x.qty)}</b><br><button class="btn" onclick="App.qty(${i},-1)">−</button> <button class="btn" onclick="App.qty(${i},1)">+</button> <button class="btn danger" onclick="App.remove(${i})">Eliminar</button></div></div>`).join('');$('modalBox').innerHTML=`<button class="close" onclick="App.closeModal()">×</button><h2>🛒 Mi carrito</h2>${rows||'<div class="empty">Tu carrito está vacío.</div>'}<div class="panel"><b>Subtotal:</b> ${money(subtotal())}<br><b>IGV (18%):</b> ${money(igv(subtotal()))}<br><h3>Total: ${money(total())}</h3><button class="primary" onclick="App.checkout()" ${db.cart.length?'':'disabled'}>Continuar al pago</button></div>`;App.openModal()},
qty(i,d){let x=db.cart[i],p=db.products.find(p=>p.id===x.id);x.qty+=d;if(x.qty<1)db.cart.splice(i,1);if(x.qty>p.stock)x.qty=p.stock;save();App.updateCart();App.cart()},remove(i){db.cart.splice(i,1);save();App.updateCart();App.cart()},
checkout(){if(!db.cart.length)return alert('El carrito está vacío.');$('modalBox').innerHTML=`<button class="close" onclick="App.closeModal()">×</button><h2>💳 Confirmar pedido</h2><div class="pay-grid"><div><h3>Paga escaneando el QR</h3><img class="qr" src="assets/qr-yape.png" alt="QR Yape SPORTS DAIRO"><p>Después de pagar, selecciona la imagen del comprobante.</p></div><div class="form"><label>Nombre completo<input id="fName"></label><label>Teléfono<input id="fPhone"></label><label>Dirección<input id="fAddress"></label><label>Documento (DNI/RUC)<input id="fDoc"></label><label class="full">Comprobante de pago<input id="fProof" type="file" accept="image/*" onchange="App.preview(event)"><img id="proofPreview" class="preview" hidden></label><div class="full"><b>Subtotal:</b> ${money(subtotal())}<br><b>IGV:</b> ${money(igv(subtotal()))}<br><h2>Total: ${money(total())}</h2></div><button class="primary full" onclick="App.placeOrder()">Enviar pedido</button></div></div>`;App.openModal()},
preview(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{$('proofPreview').src=r.result;$('proofPreview').hidden=false};r.readAsDataURL(f)},
placeOrder(){let n=$('fName').value.trim(),ph=$('fPhone').value.trim(),ad=$('fAddress').value.trim(),proof=$('fProof').files[0];if(!n||!ph||!ad)return alert('Completa nombre, teléfono y dirección.');if(!proof)return alert('Selecciona el comprobante de pago.');let id='SD-'+Date.now().toString().slice(-7), sub=subtotal(),t=total();let items=db.cart.map(x=>({...x}));items.forEach(x=>{let p=db.products.find(p=>p.id===x.id);p.stock-=x.qty});db.orders.push({id,date:new Date().toLocaleString('es-PE'),customer:n,phone:ph,address:ad,doc:$('fDoc').value,total:t,subtotal:sub,igv:igv(sub),status:'Pendiente',shalomGuide:'',items});db.sales.push({id,date:new Date().toLocaleString('es-PE'),customer:n,subtotal:sub,igv:igv(sub),total:t,payment:'QR',status:'Pagada por QR'});let c=db.customers.find(c=>c.phone===ph);if(c)Object.assign(c,{name:n,address:ad,doc:$('fDoc').value});else db.customers.push({id:Date.now(),name:n,phone:ph,address:ad,doc:$('fDoc').value});db.cart=[];save();App.updateCart();App.closeModal();alert(`Pedido ${id} registrado correctamente.\nTotal: ${money(t)}\nEstado: Pendiente`);App.admin('orders')},
openModal(){$('modal').classList.add('show')},closeModal(){$('modal').classList.remove('show')},
admin(page='dashboard'){if(!adminSession){return App.adminLoginScreen(page)} let tabs=[['dashboard','Dashboard'],['pos','Punto de Venta'],['products','Productos'],['sales','Ventas'],['orders','Pedidos'],['inventory','Inventario'],['purchases','Compras'],['customers','Clientes'],['reports','Reportes'],['settings','Configuración']];$('view').innerHTML=`<div class="admin-wrap"><div class="admin-head"><div><small>CONTROL COMERCIAL</small><h1>Sistema SPORTS DAIRO</h1></div><div class="admin-head-actions"><button class="btn" onclick="App.shop()">← Volver a tienda</button><button class="btn danger" onclick="App.logoutAdmin()">🚪 Cerrar sesión</button></div></div><div class="admin-tabs">${tabs.map(t=>`<button class="${page===t[0]?'active':''}" onclick="App.admin('${t[0]}')">${t[1]}</button>`).join('')}</div><div id="adminContent"></div></div>`;App.adminPage(page);window.scrollTo({top:0,behavior:'smooth'})},
adminPage(page){let el=$('adminContent');
if(page==='pos'){
  el.innerHTML=`<div class="pos-layout"><section class="panel pos-main"><div class="toolbar"><input id="posSearch" class="input" placeholder="Buscar por nombre, SKU o categoría" oninput="App.renderPOSProducts()"><select id="posCategory" class="input pos-select" onchange="App.renderPOSProducts()"><option value="">Todas las categorías</option>${[...new Set(db.products.map(p=>p.cat))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div id="posProducts" class="pos-products"></div></section><aside class="panel pos-ticket"><h2>🧾 Venta rápida</h2><div id="posCart"></div><div class="pos-totals"><div>Subtotal <b id="posSubtotal">S/ 0.00</b></div><div>IGV 18% <b id="posIgv">S/ 0.00</b></div><div class="grand">Total <b id="posTotal">S/ 0.00</b></div></div><div class="form pos-form"><label>Cliente<input id="posCustomer" placeholder="Consumidor final"></label><label>DNI/RUC<input id="posDoc"></label><label>Medio de pago<select id="posPayment" onchange="App.updatePOSPayment()"><option>Efectivo</option><option>Yape / Plin</option><option>Tarjeta</option><option>Transferencia</option></select></label><label>Monto recibido<input id="posPaid" type="number" step="0.01" min="0" oninput="App.updatePOSPayment()"></label><label>Vuelto<input id="posChange" value="S/ 0.00" readonly></label><button class="primary full" onclick="App.finishPOSSale()">Registrar venta</button><button class="btn full" onclick="App.clearPOS()">Vaciar venta</button></div></aside></div>`;
  App.renderPOSProducts();App.renderPOSCart();App.updatePOSPayment();return;
}
if(page==='dashboard')return el.innerHTML=`<div class="stats"><div class="stat"><small>Ventas</small><b>${db.sales.length}</b></div><div class="stat"><small>Ingresos</small><b>${money(sum(db.sales,x=>x.total))}</b></div><div class="stat"><small>Pedidos</small><b>${db.orders.length}</b></div><div class="stat"><small>Stock bajo</small><b>${db.products.filter(p=>p.stock<=p.min).length}</b></div></div><div class="panel"><h3>Resumen</h3><p>Ventas con IGV: <b>${money(sum(db.sales,x=>x.total))}</b> · IGV generado: <b>${money(sum(db.sales,x=>x.igv))}</b> · Clientes: <b>${db.customers.length}</b></p></div>`;
if(page==='products')return el.innerHTML=`<div class="panel"><div class="toolbar"><input id="pSearch" class="input" placeholder="Buscar producto" oninput="App.adminProducts()"><button class="primary" onclick="App.productForm()">＋ Nuevo producto</button></div><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Producto</th><th>Categoría</th><th>Compra</th><th>Venta</th><th>Stock</th><th>Acciones</th></tr></thead><tbody>${db.products.filter(p=>{let q=($('pSearch')?.value||'').toLowerCase();return !q||`${p.sku} ${p.name} ${p.cat}`.toLowerCase().includes(q)}).map(p=>`<tr><td>${esc(p.sku)}</td><td>${esc(p.name)}</td><td>${esc(p.cat)}</td><td>${money(p.buy)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button class="btn" onclick="App.productForm(${p.id})">Editar</button> <button class="btn danger" onclick="App.deleteProduct(${p.id})">Eliminar</button></td></tr>`).join('')}</tbody></table></div></div>`;
if(page==='sales')return el.innerHTML=`<div class="panel"><h2>Ventas</h2>${App.salesTable()}</div>`;
if(page==='orders')return el.innerHTML=`<div class="panel"><h2>📦 Pedidos</h2><p>Registra aquí el número de guía de Shalom cuando realices el envío.</p><div class="table-wrap"><table><thead><tr><th>Pedido</th><th>Fecha</th><th>Cliente</th><th>Total</th><th>Estado</th><th>Guía Shalom</th><th>Acción</th></tr></thead><tbody>${db.orders.map(o=>`<tr><td>${o.id}</td><td>${o.date}</td><td>${esc(o.customer)}</td><td>${money(o.total)}</td><td>${o.status}</td><td>${esc(o.shalomGuide||'Sin guía')}</td><td><button class="btn" onclick="App.orderStatus('${o.id}')">Estado / guía</button></td></tr>`).join('')||'<tr><td colspan="7">No hay pedidos.</td></tr>'}</tbody></table></div></div>`;
if(page==='inventory')return el.innerHTML=`<div class="panel"><h2>Inventario</h2><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Producto</th><th>Stock</th><th>Mínimo</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${db.products.map(p=>`<tr><td>${p.sku}</td><td>${esc(p.name)}</td><td>${p.stock}</td><td>${p.min}</td><td>${p.stock<=p.min?'⚠ Stock bajo':'✓ Disponible'}</td><td><button class="btn" onclick="App.adjustStock(${p.id})">Ajustar</button></td></tr>`).join('')}</tbody></table></div></div>`;
if(page==='purchases')return el.innerHTML=`<div class="panel"><div class="toolbar"><button class="primary" onclick="App.purchaseForm()">＋ Nueva compra</button></div><table><thead><tr><th>Fecha</th><th>Proveedor</th><th>Producto</th><th>Cantidad</th><th>Total</th></tr></thead><tbody>${db.purchases.map(x=>`<tr><td>${x.date}</td><td>${esc(x.supplier)}</td><td>${esc(x.product)}</td><td>${x.qty}</td><td>${money(x.total)}</td></tr>`).join('')||'<tr><td colspan="5">No hay compras.</td></tr>'}</tbody></table></div>`;
if(page==='customers')return el.innerHTML=`<div class="panel"><div class="toolbar"><button class="primary" onclick="App.customerForm()">＋ Nuevo cliente</button></div><table><thead><tr><th>Nombre</th><th>DNI/RUC</th><th>Teléfono</th><th>Dirección</th><th>Acción</th></tr></thead><tbody>${db.customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.doc)}</td><td>${esc(c.phone)}</td><td>${esc(c.address)}</td><td><button class="btn" onclick="App.customerForm(${c.id})">Editar</button></td></tr>`).join('')||'<tr><td colspan="5">No hay clientes.</td></tr>'}</tbody></table></div>`;
if(page==='reports')return el.innerHTML=`<div class="stats"><div class="stat"><small>Ventas sin IGV</small><b>${money(sum(db.sales,x=>x.subtotal))}</b></div><div class="stat"><small>IGV</small><b>${money(sum(db.sales,x=>x.igv))}</b></div><div class="stat"><small>Ventas con IGV</small><b>${money(sum(db.sales,x=>x.total))}</b></div><div class="stat"><small>Compras</small><b>${money(sum(db.purchases,x=>x.total))}</b></div></div><div class="panel"><button class="primary" onclick="App.csv()">Descargar reporte CSV</button></div>`;
if(page==='settings')return el.innerHTML=`<div class="panel"><h2>Datos de empresa</h2><p><b>SPORTS DAIRO</b><br>RUC 10757165530<br>Dairo.kick@gmail.com<br>928 469 185<br>Ica, Chincha Alta</p><p><b>Envíos:</b> Shalom</p><a class="primary" href="https://www.shalom.com.pe/rastrea" target="_blank" rel="noopener">📦 Abrir rastreo oficial de Shalom</a></div>`;
},
adminProducts(){App.adminPage('products')},salesTable(){return `<div class="table-wrap"><table><thead><tr><th>ID</th><th>Fecha</th><th>Cliente</th><th>Subtotal</th><th>IGV</th><th>Total</th><th>Pago</th></tr></thead><tbody>${db.sales.map(s=>`<tr><td>${s.id}</td><td>${s.date}</td><td>${esc(s.customer)}</td><td>${money(s.subtotal)}</td><td>${money(s.igv)}</td><td>${money(s.total)}</td><td>${s.payment}</td></tr>`).join('')||'<tr><td colspan="7">No hay ventas.</td></tr>'}</tbody></table></div>`},
posCart:[],
renderPOSProducts(){let q=($('posSearch')?.value||'').toLowerCase(),cat=$('posCategory')?.value||'',a=db.products.filter(p=>(!cat||p.cat===cat)&&(`${p.name} ${p.sku} ${p.cat}`).toLowerCase().includes(q));let box=$('posProducts');if(!box)return;box.innerHTML=a.map(p=>`<button class="pos-product" onclick="App.addPOS(${p.id})" ${p.stock<1?'disabled':''}><span class="pos-emoji">${p.emoji||'📦'}</span><span><b>${esc(p.name)}</b><small>${esc(p.sku)} · ${esc(p.cat)}</small><strong>${money(p.price)}</strong><small>Stock: ${p.stock}</small></span></button>`).join('')||'<div class="empty">No hay productos.</div>'},
addPOS(id){let p=db.products.find(x=>x.id===id);if(!p||p.stock<1)return;let x=this.posCart.find(x=>x.id===id);if(x){if(x.qty>=p.stock)return alert('No hay más stock disponible.');x.qty++}else this.posCart.push({id:p.id,name:p.name,price:p.price,qty:1});this.renderPOSCart()},
renderPOSCart(){let box=$('posCart');if(!box)return;box.innerHTML=this.posCart.length?this.posCart.map((x,i)=>`<div class="pos-line"><div><b>${esc(x.name)}</b><small>${money(x.price)} c/u</small></div><div class="pos-actions"><button class="btn" onclick="App.qtyPOS(${i},-1)">−</button><b>${x.qty}</b><button class="btn" onclick="App.qtyPOS(${i},1)">+</button><button class="btn danger" onclick="App.removePOS(${i})">×</button></div><strong>${money(x.price*x.qty)}</strong></div>`).join(''):'<div class="empty">Agrega productos a la venta.</div>';let sub=sum(this.posCart,x=>x.price*x.qty);if($('posSubtotal'))$('posSubtotal').textContent=money(sub);if($('posIgv'))$('posIgv').textContent=money(igv(sub));if($('posTotal'))$('posTotal').textContent=money(+(sub+igv(sub)).toFixed(2));this.updatePOSPayment()},
qtyPOS(i,d){let x=this.posCart[i],p=db.products.find(p=>p.id===x.id);if(!x)return;x.qty+=d;if(x.qty<1)this.posCart.splice(i,1);if(x.qty>p.stock)x.qty=p.stock;this.renderPOSCart()},
removePOS(i){this.posCart.splice(i,1);this.renderPOSCart()},
clearPOS(){this.posCart=[];if($('posCustomer'))$('posCustomer').value='';if($('posDoc'))$('posDoc').value='';if($('posPaid'))$('posPaid').value='';this.renderPOSCart()},
updatePOSPayment(){let t=+(sum(this.posCart,x=>x.price*x.qty)+igv(sum(this.posCart,x=>x.price*x.qty))).toFixed(2),paid=+$('posPaid')?.value||0;let change=Math.max(0,paid-t);if($('posChange'))$('posChange').value=money(change)},
finishPOSSale(){if(!this.posCart.length)return alert('Agrega al menos un producto.');let sub=sum(this.posCart,x=>x.price*x.qty),tax=igv(sub),t=+(sub+tax).toFixed(2),pay=$('posPayment').value,paid=+$('posPaid').value||0;if(pay==='Efectivo'&&paid<t)return alert(`El monto recibido es menor al total de ${money(t)}.`);if(pay!=='Efectivo'&&paid<t)paid=t;let items=this.posCart.map(x=>({...x}));for(const x of items){let p=db.products.find(p=>p.id===x.id);if(!p||p.stock<x.qty)return alert(`Stock insuficiente para ${x.name}.`)}items.forEach(x=>db.products.find(p=>p.id===x.id).stock-=x.qty);let id='V-'+Date.now().toString().slice(-7),customer=$('posCustomer').value.trim()||'Consumidor final',doc=$('posDoc').value.trim();db.sales.push({id,date:new Date().toLocaleString('es-PE'),customer,doc,subtotal:sub,igv:tax,total:t,payment:pay,status:'Pagada',items});if(customer!=='Consumidor final'){let c=db.customers.find(c=>doc&&c.doc===doc);if(c)Object.assign(c,{name:customer,doc,phone:c.phone||'',address:c.address||''});else db.customers.push({id:Date.now(),name:customer,doc,phone:'',address:''})}save();let change=Math.max(0,paid-t);this.posCart=[];this.renderPOSProducts();this.renderPOSCart();if($('posCustomer'))$('posCustomer').value='';if($('posDoc'))$('posDoc').value='';if($('posPaid'))$('posPaid').value='';alert(`Venta ${id} registrada correctamente.\nSubtotal: ${money(sub)}\nIGV: ${money(tax)}\nTotal: ${money(t)}\nVuelto: ${money(change)}`);this.admin('sales')},
adminLoginScreen(page='dashboard'){
  $('view').innerHTML=`<section class="admin-login-page">
    <div class="admin-login-card">
      <img src="assets/logo-sports-dairo.png" class="admin-login-brand" alt="SPORTS DAIRO">
      <div class="login-logo">🔐</div>
      <h1>Acceso de administrador</h1>
      <p>Ingresa para administrar productos, ventas, pedidos, inventario y reportes.</p>
      <form onsubmit="event.preventDefault();App.adminLogin('${page}')">
        <label>Usuario<input id="adminUser" autocomplete="username" placeholder="Usuario" autofocus></label>
        <label>Contraseña<input id="adminPass" type="password" autocomplete="current-password" placeholder="Contraseña"></label>
        <button class="primary full" type="submit">Ingresar al panel</button>
      </form>
      <div class="login-help"><b>Usuario:</b> admin<br><b>Contraseña:</b> admin123</div>
      <button class="btn full" onclick="App.shop()">← Volver a la tienda</button>
    </div>
  </section>`;
  const pass=$('adminPass'); if(pass) pass.focus();
},
adminLogin(page='dashboard'){
  let u=$('adminUser')?.value.trim(),p=$('adminPass')?.value;
  if(u===ADMIN_USER&&p===ADMIN_PASS){
    adminSession=true;
    localStorage.setItem('sports_dairo_admin_session','1');
    App.admin(page||'dashboard');
  }else{
    alert('Usuario o contraseña incorrectos.');
    $('adminPass')?.focus();
  }
},
logoutAdmin(){adminSession=false;localStorage.removeItem('sports_dairo_admin_session');App.shop();},
productForm(id){let p=id?db.products.find(x=>x.id===id):{sku:'',name:'',cat:'Ropa',buy:0,price:0,stock:0,min:1,emoji:'📦'};$('modalBox').innerHTML=`<button class="close" onclick="App.closeModal()">×</button><h2>${id?'Editar':'Nuevo'} producto</h2><div class="form"><label>SKU<input id="pfSku" value="${esc(p.sku)}"></label><label>Nombre<input id="pfName" value="${esc(p.name)}"></label><label>Categoría<select id="pfCat">${['Calzado','Ropa','Fútbol','Accesorios','Tecnología','Artefactos','Otros'].map(c=>`<option ${p.cat===c?'selected':''}>${c}</option>`).join('')}</select></label><label>Emoji<input id="pfEmoji" value="${esc(p.emoji||'📦')}"></label><label>Precio compra<input id="pfBuy" type="number" step="0.01" value="${p.buy}"></label><label>Precio venta<input id="pfPrice" type="number" step="0.01" value="${p.price}"></label><label>Stock<input id="pfStock" type="number" value="${p.stock}"></label><label>Stock mínimo<input id="pfMin" type="number" value="${p.min}"></label><button class="primary full" onclick="App.saveProduct(${id||0})">Guardar producto</button></div>`;App.openModal()},
saveProduct(id){let x={sku:$('pfSku').value.trim(),name:$('pfName').value.trim(),cat:$('pfCat').value,buy:+$('pfBuy').value||0,price:+$('pfPrice').value||0,stock:+$('pfStock').value||0,min:+$('pfMin').value||0,emoji:$('pfEmoji').value||'📦'};if(!x.sku||!x.name)return alert('SKU y nombre son obligatorios.');if(id)Object.assign(db.products.find(p=>p.id===id),x);else db.products.push({id:Date.now(),...x});save();App.closeModal();App.admin('products')},
deleteProduct(id){if(!confirm('¿Eliminar este producto?'))return;db.products=db.products.filter(p=>p.id!==id);db.cart=db.cart.filter(x=>x.id!==id);save();App.admin('products');App.updateCart()},
adjustStock(id){let p=db.products.find(x=>x.id===id),n=prompt(`Nuevo stock para ${p.name}:`,p.stock);if(n!==null&&n!==''){p.stock=Math.max(0,+n||0);save();App.admin('inventory')}},
orderStatus(id){let o=db.orders.find(x=>x.id===id);if(!o)return;let s=prompt('Estado: Pendiente / Preparando / Enviado / Entregado / Cancelado',o.status);if(s===null)return;let g=prompt('Número de guía Shalom (opcional):',o.shalomGuide||'');o.status=s.trim()||o.status;o.shalomGuide=(g||'').trim();save();App.admin('orders')},
trackOrder(){$('modalBox').innerHTML=`<button class="close" onclick="App.closeModal()">×</button><h2>📦 Rastrear pedido</h2><p>Consulta el estado de tu pedido SPORTS DAIRO y, si ya fue enviado, rastrea la guía en Shalom.</p><label class="track-label">Número de pedido<input id="trackId" class="input" placeholder="Ej. SD-1234567"></label><button class="primary full" onclick="App.findOrder()">Consultar pedido</button><div id="trackResult" class="panel" style="margin-top:12px"></div><a class="btn full" href="https://www.shalom.com.pe/rastrea" target="_blank" rel="noopener">🚚 Rastrear en Shalom</a>`;App.openModal()},
findOrder(){let id=($('trackId')?.value||'').trim().toUpperCase(),o=db.orders.find(x=>String(x.id).toUpperCase()===id);let box=$('trackResult');if(!box)return;if(!o){box.innerHTML='<b>No encontramos ese pedido.</b><br>Verifica el número de pedido.';return}box.innerHTML=`<b>Pedido:</b> ${esc(o.id)}<br><b>Cliente:</b> ${esc(o.customer)}<br><b>Estado:</b> ${esc(o.status)}<br><b>Guía Shalom:</b> ${esc(o.shalomGuide||'Aún no registrada')}<br>${o.shalomGuide?'<a class="btn" href="https://www.shalom.com.pe/rastrea" target="_blank" rel="noopener">Abrir rastreo Shalom</a>':'Cuando se registre la guía, podrás rastrearla en Shalom.'}`},
purchaseForm(){ $('modalBox').innerHTML=`<button class="close" onclick="App.closeModal()">×</button><h2>Nueva compra</h2><div class="form"><label>Proveedor<input id="buySup"></label><label>Producto<select id="buyProd">${db.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Cantidad<input id="buyQty" type="number" value="1" min="1"></label><label>Precio unitario<input id="buyPrice" type="number" step="0.01" value="0"></label><button class="primary full" onclick="App.savePurchase()">Registrar compra</button></div>`;App.openModal()},
savePurchase(){let p=db.products.find(p=>p.id==$('buyProd').value),q=+$('buyQty').value||0,price=+$('buyPrice').value||p.buy;if(!q)return alert('Cantidad inválida.');p.stock+=q;db.purchases.push({date:new Date().toLocaleString('es-PE'),supplier:$('buySup').value||'Proveedor general',product:p.name,qty:q,total:+(q*price).toFixed(2)});save();App.closeModal();App.admin('purchases')},
customerForm(id){let c=id?db.customers.find(x=>x.id==id):{name:'',doc:'',phone:'',address:''};$('modalBox').innerHTML=`<button class="close" onclick="App.closeModal()">×</button><h2>${id?'Editar':'Nuevo'} cliente</h2><div class="form"><label>Nombre<input id="cfName" value="${esc(c.name)}"></label><label>DNI/RUC<input id="cfDoc" value="${esc(c.doc)}"></label><label>Teléfono<input id="cfPhone" value="${esc(c.phone)}"></label><label>Dirección<input id="cfAddress" value="${esc(c.address)}"></label><button class="primary full" onclick="App.saveCustomer(${id||0})">Guardar cliente</button></div>`;App.openModal()},
saveCustomer(id){let x={name:$('cfName').value.trim(),doc:$('cfDoc').value.trim(),phone:$('cfPhone').value.trim(),address:$('cfAddress').value.trim()};if(!x.name)return alert('Nombre obligatorio.');if(id)Object.assign(db.customers.find(c=>c.id==id),x);else db.customers.push({id:Date.now(),...x});save();App.closeModal();App.admin('customers')},
csv(){let lines=[['ID','Fecha','Cliente','Subtotal','IGV','Total','Pago'],...db.sales.map(s=>[s.id,s.date,s.customer,s.subtotal,s.igv,s.total,s.payment])];let csv=lines.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='reporte-ventas-sports-dairo.csv';a.click();URL.revokeObjectURL(a.href)},reset(){if(confirm('¿Borrar todos los datos y volver al catálogo inicial?')){localStorage.removeItem(KEY);location.reload()}}
};
$('search').addEventListener('input',()=>{if($('grid'))App.renderProducts()});
App.shop();App.updateCart();

window.App=App; window.requireAdmin=requireAdmin;
